name: Linux browsers
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install sitespeed.io
      run: |
        cd .. 
        git clone https://github.com/sitespeedio/sitespeed.io.git
        cd sitespeed.io
        npm install -g 
        cd ../plugin-webpagetest
    - name: Run tests on WebPageTest
      run: sitespeed.io --plugins.add . --plugins.remove browsertime https://www.sitespeed.io/ --webpagetest.key ${{ secrets.WPT_KEY }}
    